# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-11 09:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaIndustry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u540d\u79f0')),
                ('status', models.CharField(default='', max_length=255, verbose_name='\u72b6\u6001')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Area', verbose_name='\u5730\u57df')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Industry', verbose_name='\u884c\u4e1a')),
            ],
            options={
                'verbose_name_plural': '\u5730\u57df\u884c\u4e1a',
            },
        ),
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k', models.CharField(max_length=255, verbose_name='\u952e')),
                ('v', models.TextField(blank=True, verbose_name='\u503c')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'verbose_name_plural': '\u7f13\u5b58',
            },
        ),
        migrations.CreateModel(
            name='CacheConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u540d\u79f0')),
                ('days', models.IntegerField(verbose_name='\u95f4\u9694\u5929\u6570')),
                ('params', models.TextField(blank=True, verbose_name='\u53c2\u6570')),
            ],
            options={
                'verbose_name_plural': '\u7f13\u5b58\u914d\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='ConsumeIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force', models.IntegerField(blank=True, choices=[(0, '\u65e0'), (1, '\u6709')], null=True, verbose_name='\u56fd\u5bb6\u5f3a\u5236\u6027\u8981\u6c42')),
                ('close', models.IntegerField(blank=True, choices=[(1, '\u4f4e'), (2, '\u4e2d'), (3, '\u9ad8')], null=True, verbose_name='\u5bc6\u5207\u7a0b\u5ea6')),
                ('consume', models.IntegerField(blank=True, choices=[(0, '\u5426'), (1, '\u662f')], null=True, verbose_name='\u6d89\u53ca\u7279\u5b9a\u6d88\u8d39\u7fa4\u4f53\u548c\u7279\u6b8a\u8981\u6c42')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='\u5e74\u5ea6')),
                ('area', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Area', verbose_name='\u5730\u57df')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Industry', verbose_name='\u884c\u4e1a')),
            ],
            options={
                'verbose_name_plural': '\u6d88\u8d39\u6307\u6807(\u7ef4)',
            },
        ),
        migrations.CreateModel(
            name='ManageIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence', models.IntegerField(blank=True, choices=[(0, '\u5426'), (1, '\u662f')], null=True, verbose_name='\u5217\u5165\u8bb8\u53ef\u8bc1\u76ee\u5f55')),
                ('productauth', models.IntegerField(blank=True, choices=[(0, '\u5426'), (1, '\u662f')], null=True, verbose_name='\u5217\u5165\u4ea7\u54c1\u8ba4\u8bc1\u76ee\u5f55')),
                ('encourage', models.IntegerField(blank=True, choices=[(0, '\u5426'), (1, '\u662f')], null=True, verbose_name='\u662f\u5426\u9f13\u52b1')),
                ('limit', models.IntegerField(blank=True, choices=[(0, '\u5426'), (1, '\u662f')], null=True, verbose_name='\u662f\u5426\u9650\u5236')),
                ('remove', models.IntegerField(blank=True, choices=[(0, '\u5426'), (1, '\u662f')], null=True, verbose_name='\u662f\u5426\u6dd8\u6c70')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='\u5e74\u5ea6')),
                ('area', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Area', verbose_name='\u5730\u57df')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Industry', verbose_name='\u884c\u4e1a')),
            ],
            options={
                'verbose_name_plural': '\u7ba1\u7406\u6307\u6807(\u7ef4)',
            },
        ),
        migrations.CreateModel(
            name='ModelWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consume_index', models.FloatField(verbose_name='\u6d88\u8d39\u6307\u6807(\u7ef4)')),
                ('society_index', models.FloatField(verbose_name='\u793e\u4f1a\u6027\u6307\u6807(\u7ef4)')),
                ('manage_index', models.FloatField(verbose_name='\u7ba1\u7406\u6307\u6807(\u7ef4)')),
                ('risk_news_index', models.FloatField(verbose_name='\u65b0\u95fb\u6307\u6807(\u7ef4)')),
                ('inspection_index', models.FloatField(verbose_name='\u62bd\u68c0\u6307\u6807(\u7ef4)')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Area', verbose_name='\u5730\u57df')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Industry', verbose_name='\u884c\u4e1a')),
            ],
            options={
                'verbose_name_plural': '\u6a21\u578b\u6743\u91cd',
            },
        ),
        migrations.CreateModel(
            name='RiskEnterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255, verbose_name='\u98ce\u9669\u4ea7\u54c1\u540d\u79f0')),
                ('issues', models.CharField(blank=True, max_length=255, verbose_name='\u98ce\u9669\u4e8b\u9879')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Enterprise', verbose_name='\u4f01\u4e1a\u540d\u79f0')),
            ],
            options={
                'verbose_name_plural': '\u4f01\u4e1a\u98ce\u9669',
            },
        ),
        migrations.CreateModel(
            name='SocietyIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade', models.IntegerField(blank=True, choices=[(1, '\u4f4e'), (2, '\u4e2d'), (3, '\u9ad8')], null=True, verbose_name='\u8d38\u6613\u91cf')),
                ('qualified', models.IntegerField(blank=True, choices=[(1, '\u4f4e'), (2, '\u4e2d'), (3, '\u9ad8')], null=True, verbose_name='\u62bd\u68c0\u5408\u683c\u7387')),
                ('accident', models.IntegerField(blank=True, choices=[(1, '\u4f4e'), (2, '\u4e2d'), (3, '\u9ad8')], null=True, verbose_name='\u6848\u4f8b\u53d1\u751f\u72b6\u51b5')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='\u5e74\u5ea6')),
                ('area', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Area', verbose_name='\u5730\u57df')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Industry', verbose_name='\u884c\u4e1a')),
            ],
            options={
                'verbose_name_plural': '\u793e\u4f1a\u6027\u6307\u6807(\u7ef4)',
            },
        ),
        migrations.CreateModel(
            name='UserArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Area', verbose_name='\u5730\u57df')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'verbose_name_plural': '\u7528\u6237\u5730\u57df\u5f31\u5173\u8054',
            },
        ),
    ]
