# Generated by Django 2.0 on 2017-12-13 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaIndustry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('status', models.CharField(default='', max_length=255, verbose_name='状态')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Area', verbose_name='地域')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Industry', verbose_name='行业')),
            ],
            options={
                'verbose_name_plural': '地域行业',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_article', models.CharField(max_length=32, verbose_name='基础文章库')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seer_category', to='base.ArticleCategory', verbose_name='文章类别')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Enterprise', verbose_name='企业')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Industry', verbose_name='行业')),
            ],
            options={
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k', models.CharField(max_length=255, verbose_name='键')),
                ('v', models.TextField(blank=True, verbose_name='值')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '缓存',
            },
        ),
        migrations.CreateModel(
            name='CacheConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('days', models.IntegerField(verbose_name='间隔天数')),
                ('params', models.TextField(blank=True, verbose_name='参数')),
            ],
            options={
                'verbose_name_plural': '缓存配置',
            },
        ),
        migrations.CreateModel(
            name='ConsumeIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force', models.IntegerField(blank=True, choices=[(0, '无'), (1, '有')], null=True, verbose_name='国家强制性要求')),
                ('close', models.IntegerField(blank=True, choices=[(1, '低'), (2, '中'), (3, '高')], null=True, verbose_name='密切程度')),
                ('consume', models.IntegerField(blank=True, choices=[(0, '否'), (1, '是')], null=True, verbose_name='涉及特定消费群体和特殊要求')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='年度')),
                ('area', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Area', verbose_name='地域')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Industry', verbose_name='行业')),
            ],
            options={
                'verbose_name_plural': '消费指标(维)',
            },
        ),
        migrations.CreateModel(
            name='IndustryScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.BigIntegerField(verbose_name='分值')),
                ('time', models.DateField(verbose_name='日期')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Area', verbose_name='地域')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Industry', verbose_name='行业')),
            ],
            options={
                'verbose_name_plural': '行业分值',
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_inspection', models.CharField(max_length=32, verbose_name='基础抽检库')),
                ('enterprise_qualified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualitieds', to='base.Enterprise', verbose_name='合格企业')),
                ('enterprise_unqualified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unqualifieds', to='base.Enterprise', verbose_name='不合格企业')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Industry', verbose_name='行业')),
            ],
            options={
                'verbose_name_plural': '抽检信息',
            },
        ),
        migrations.CreateModel(
            name='ManageIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence', models.IntegerField(blank=True, choices=[(0, '否'), (1, '是')], null=True, verbose_name='列入许可证目录')),
                ('productauth', models.IntegerField(blank=True, choices=[(0, '否'), (1, '是')], null=True, verbose_name='列入产品认证目录')),
                ('encourage', models.IntegerField(blank=True, choices=[(0, '否'), (1, '是')], null=True, verbose_name='是否鼓励')),
                ('limit', models.IntegerField(blank=True, choices=[(0, '否'), (1, '是')], null=True, verbose_name='是否限制')),
                ('remove', models.IntegerField(blank=True, choices=[(0, '否'), (1, '是')], null=True, verbose_name='是否淘汰')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='年度')),
                ('area', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Area', verbose_name='地域')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Industry', verbose_name='行业')),
            ],
            options={
                'verbose_name_plural': '管理指标(维)',
            },
        ),
        migrations.CreateModel(
            name='ModelWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consume_index', models.FloatField(verbose_name='消费指标(维)')),
                ('society_index', models.FloatField(verbose_name='社会性指标(维)')),
                ('manage_index', models.FloatField(verbose_name='管理指标(维)')),
                ('risk_news_index', models.FloatField(verbose_name='新闻指标(维)')),
                ('inspection_index', models.FloatField(verbose_name='抽检指标(维)')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Area', verbose_name='地域')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Industry', verbose_name='行业')),
            ],
            options={
                'verbose_name_plural': '模型权重',
            },
        ),
        migrations.CreateModel(
            name='RiskEnterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255, verbose_name='风险产品名称')),
                ('issues', models.CharField(blank=True, max_length=255, verbose_name='风险事项')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Enterprise', verbose_name='企业名称')),
            ],
            options={
                'verbose_name_plural': '企业风险',
            },
        ),
        migrations.CreateModel(
            name='SocietyIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade', models.IntegerField(blank=True, choices=[(1, '低'), (2, '中'), (3, '高')], null=True, verbose_name='贸易量')),
                ('qualified', models.IntegerField(blank=True, choices=[(1, '低'), (2, '中'), (3, '高')], null=True, verbose_name='抽检合格率')),
                ('accident', models.IntegerField(blank=True, choices=[(1, '低'), (2, '中'), (3, '高')], null=True, verbose_name='案例发生状况')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='年度')),
                ('area', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Area', verbose_name='地域')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Industry', verbose_name='行业')),
            ],
            options={
                'verbose_name_plural': '社会性指标(维)',
            },
        ),
        migrations.CreateModel(
            name='UserArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Area', verbose_name='地域')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '用户地域弱关联',
            },
        ),
    ]
