image: base:v1
before_script:
  - apt-get update -yq
  - apt-get install -y python-dev python-pip python-mysqldb

stages:
  - test

test:
  stage: test
  script:
    - pip install -r requirement.txt
    - python manage.py test
  only:
    - master
  tags:
    - docker