# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-04-25 09:08
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('origin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaIndustry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u540d\u79f0')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='origin.Area', verbose_name='\u5730\u57df')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='origin.Industry', verbose_name='\u884c\u4e1a')),
            ],
            options={
                'verbose_name_plural': '\u5730\u57df\u884c\u4e1a',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zh_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4e2d\u6587\u540d\u79f0')),
                ('en_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u82f1\u6587\u540d\u79f0')),
                ('logo', models.URLField(verbose_name='\u56fe\u6807')),
            ],
            options={
                'db_table': 'brand',
                'verbose_name_plural': '\u54c1\u724c',
            },
        ),
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k', models.CharField(max_length=255, verbose_name='\u952e')),
                ('v', models.TextField(blank=True, verbose_name='\u503c')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'verbose_name_plural': '\u7f13\u5b58',
            },
        ),
        migrations.CreateModel(
            name='CacheConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u540d\u79f0')),
                ('days', models.IntegerField(verbose_name='\u95f4\u9694\u5929\u6570')),
                ('params', models.TextField(blank=True, verbose_name='\u53c2\u6570')),
            ],
            options={
                'verbose_name_plural': '\u7f13\u5b58\u914d\u7f6e',
            },
        ),
        migrations.CreateModel(
            name='ConsumeIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force', models.IntegerField(blank=True, choices=[(0, '\u65e0'), (1, '\u6709')], null=True, verbose_name='\u56fd\u5bb6\u5f3a\u5236\u6027\u8981\u6c42')),
                ('close', models.IntegerField(blank=True, choices=[(1, '\u4f4e'), (2, '\u4e2d'), (3, '\u9ad8')], null=True, verbose_name='\u5bc6\u5207\u7a0b\u5ea6')),
                ('consume', models.IntegerField(blank=True, choices=[(0, '\u5426'), (1, '\u662f')], null=True, verbose_name='\u6d89\u53ca\u7279\u5b9a\u6d88\u8d39\u7fa4\u4f53\u548c\u7279\u6b8a\u8981\u6c42')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='\u5e74\u5ea6')),
                ('area', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='origin.Area', verbose_name='\u5730\u57df')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='origin.Industry', verbose_name='\u884c\u4e1a')),
            ],
            options={
                'db_table': 'consume_index',
                'verbose_name_plural': '\u6d88\u8d39\u6307\u6807(\u7ef4)',
            },
        ),
        migrations.CreateModel(
            name='InternetScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='\u4e92\u8054\u7f51\u5206\u6570')),
                ('pubtime', models.DateField(default=datetime.date.today, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name_plural': '\u4e92\u8054\u7f51\u5206\u6570',
            },
        ),
        migrations.CreateModel(
            name='ManageIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence', models.IntegerField(blank=True, choices=[(0, '\u5426'), (1, '\u662f')], null=True, verbose_name='\u5217\u5165\u8bb8\u53ef\u8bc1\u76ee\u5f55')),
                ('productauth', models.IntegerField(blank=True, choices=[(0, '\u5426'), (1, '\u662f')], null=True, verbose_name='\u5217\u5165\u4ea7\u54c1\u8ba4\u8bc1\u76ee\u5f55')),
                ('encourage', models.IntegerField(blank=True, choices=[(0, '\u5426'), (1, '\u662f')], null=True, verbose_name='\u662f\u5426\u9f13\u52b1')),
                ('limit', models.IntegerField(blank=True, choices=[(0, '\u5426'), (1, '\u662f')], null=True, verbose_name='\u662f\u5426\u9650\u5236')),
                ('remove', models.IntegerField(blank=True, choices=[(0, '\u5426'), (1, '\u662f')], null=True, verbose_name='\u662f\u5426\u6dd8\u6c70')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='\u5e74\u5ea6')),
                ('area', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='origin.Area', verbose_name='\u5730\u57df')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='origin.Industry', verbose_name='\u884c\u4e1a')),
            ],
            options={
                'db_table': 'manage_index',
                'verbose_name_plural': '\u7ba1\u7406\u6307\u6807(\u7ef4)',
            },
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u6307\u6807')),
                ('level', models.BigIntegerField(verbose_name='\u7b49\u7ea7')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riskmonitor.Metrics', verbose_name='\u4e0a\u4e00\u7ea7')),
            ],
            options={
                'db_table': 'metrics',
                'verbose_name_plural': '\u6307\u6807',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u751f\u4ea7\u4ea7\u54c1')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='origin.Enterprise', verbose_name='\u4f01\u4e1a')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='origin.Industry', verbose_name='\u4ea7\u54c1')),
            ],
            options={
                'db_table': 'product',
                'verbose_name_plural': '\u751f\u4ea7\u4ea7\u54c1',
            },
        ),
        migrations.CreateModel(
            name='ProductKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newkeyword', models.CharField(max_length=255, verbose_name='\u5173\u952e\u8bcd')),
                ('review', models.CharField(default='', max_length=255, verbose_name='\u5ba1\u6838')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Group')),
                ('product', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='riskmonitor.Product')),
            ],
            options={
                'db_table': 'product_keyword',
                'verbose_name_plural': '\u4ea7\u54c1\u76d1\u6d4b\u5173\u952e\u8bcd',
            },
        ),
        migrations.CreateModel(
            name='ProductMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=255, verbose_name='\u6743\u91cd')),
                ('metrics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskmonitor.Metrics', verbose_name='\u6307\u6807')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskmonitor.Product', verbose_name='\u4ea7\u54c1')),
            ],
            options={
                'db_table': 'metrics_product',
                'verbose_name_plural': '\u4ea7\u54c1\u6307\u6807',
            },
        ),
        migrations.CreateModel(
            name='RiskData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4f5c\u8005\u94fe\u63a5\u5730\u5740')),
                ('user_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4f5c\u8005\u540d')),
                ('content', models.TextField(blank=True, verbose_name='\u6b63\u6587')),
                ('pubtime', models.DateTimeField(blank=True, null=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('comment', models.CharField(max_length=255, verbose_name='\u662f\u5426\u81ea\u8425')),
                ('comment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u8bc4\u8bba\u5730\u5740')),
                ('source', models.CharField(blank=True, max_length=255, verbose_name='\u4fe1\u606f\u6765\u6e90')),
                ('show_pic', models.TextField(blank=True, null=True, verbose_name='\u56fe\u7247\u8bc4\u8bba\u56fe')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='\u8bc4\u5206')),
                ('url', models.URLField(blank=True, null=True, verbose_name='\u7f51\u7ad9\u94fe\u63a5')),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=255, verbose_name='uuid')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='origin.Area', verbose_name='\u5730\u57df')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskmonitor.Brand', verbose_name='\u54c1\u724c')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='origin.Industry', verbose_name='\u884c\u4e1a')),
            ],
            options={
                'db_table': 'risk_data',
                'verbose_name_plural': '\u7535\u5546\u98ce\u9669\u8bc4\u8bba',
            },
        ),
        migrations.CreateModel(
            name='RiskNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='\u6807\u9898')),
                ('url', models.URLField(verbose_name='\u7f51\u7ad9\u94fe\u63a5')),
                ('content', tinymce.models.HTMLField(blank=True, verbose_name='\u6b63\u6587')),
                ('pubtime', models.DateTimeField(verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('reprinted', models.IntegerField(verbose_name='\u8f6c\u8f7d\u6570')),
                ('is_delete', models.BooleanField(default=0, verbose_name='\u662f\u5426\u5220\u9664')),
                ('risk_keyword', models.CharField(blank=True, default='', max_length=255, verbose_name='\u98ce\u9669\u65b0\u95fb\u5173\u952e\u8bcd')),
                ('invalid_keyword', models.CharField(blank=True, default='', max_length=255, verbose_name='\u65e0\u6548\u5173\u952e\u8bcd')),
                ('area', models.ManyToManyField(related_name='rareas', related_query_name=b'rarea', to='origin.Area', verbose_name='\u5730\u57df')),
                ('enterprise', models.ManyToManyField(related_name='enterprises', related_query_name=b'enterprise', to='origin.Enterprise', verbose_name='\u4f01\u4e1a')),
                ('industry', models.ManyToManyField(related_name='industrys', related_query_name=b'industry', to='origin.Industry', verbose_name='\u884c\u4e1a')),
            ],
            options={
                'ordering': ['-pubtime'],
                'db_table': 'risk_news',
                'verbose_name_plural': '\u98ce\u9669\u65b0\u95fb',
            },
        ),
        migrations.CreateModel(
            name='RiskNewsPublisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u53d1\u5e03\u8005')),
            ],
            options={
                'db_table': 'risk_news_publisher',
                'verbose_name_plural': '\u98ce\u9669\u65b0\u95fb\u53d1\u5e03\u8005',
            },
        ),
        migrations.CreateModel(
            name='ScoreEnterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='\u5206\u503c')),
                ('pubtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('increment', models.IntegerField(default=0, verbose_name='\u589e\u91cf')),
                ('reducescore', models.IntegerField(default=0, verbose_name='\u6240\u51cf\u7684\u5206\u6570')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='origin.Enterprise', verbose_name='\u4f01\u4e1a')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'db_table': 'score_enterprise',
                'verbose_name_plural': '\u4f01\u4e1a\u5206\u503c',
            },
        ),
        migrations.CreateModel(
            name='ScoreIndustry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='\u5206\u503c')),
                ('pubtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('increment', models.IntegerField(default=0, verbose_name='\u589e\u91cf')),
                ('reducescore', models.IntegerField(default=0, verbose_name='\u6240\u51cf\u7684\u5206\u6570')),
                ('industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='origin.Industry', verbose_name='\u884c\u4e1a')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'db_table': 'score_industry',
                'verbose_name_plural': '\u884c\u4e1a\u5206\u503c',
            },
        ),
        migrations.CreateModel(
            name='ScoreProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=255, verbose_name='\u5206\u503c')),
                ('pubtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskmonitor.Product', verbose_name='\u4ea7\u54c1')),
            ],
            options={
                'db_table': 'score_product',
                'verbose_name_plural': '\u4ea7\u54c1\u5206\u503c',
            },
        ),
        migrations.CreateModel(
            name='SocietyIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade', models.IntegerField(blank=True, choices=[(1, '\u4f4e'), (2, '\u4e2d'), (3, '\u9ad8')], null=True, verbose_name='\u8d38\u6613\u91cf')),
                ('qualified', models.IntegerField(blank=True, choices=[(1, '\u4f4e'), (2, '\u4e2d'), (3, '\u9ad8')], null=True, verbose_name='\u62bd\u68c0\u5408\u683c\u7387')),
                ('accident', models.IntegerField(blank=True, choices=[(1, '\u4f4e'), (2, '\u4e2d'), (3, '\u9ad8')], null=True, verbose_name='\u6848\u4f8b\u53d1\u751f\u72b6\u51b5')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='\u5e74\u5ea6')),
                ('area', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='origin.Area', verbose_name='\u5730\u57df')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='origin.Industry', verbose_name='\u884c\u4e1a')),
            ],
            options={
                'db_table': 'society_index',
                'verbose_name_plural': '\u793e\u4f1a\u6027\u6307\u6807(\u7ef4)',
            },
        ),
        migrations.CreateModel(
            name='SummariesScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='\u6574\u4f53\u5206\u6570')),
                ('pubtime', models.DateField(default=datetime.date.today, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name_plural': '\u6574\u4f53\u5206\u6570',
            },
        ),
        migrations.CreateModel(
            name='UserArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='origin.Area', verbose_name='\u5730\u57df')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'db_table': 'user_area',
                'verbose_name_plural': '\u7528\u6237\u5730\u57df\u5f31\u5173\u8054',
            },
        ),
        migrations.CreateModel(
            name='UserEnterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='origin.Enterprise', verbose_name='\u4f01\u4e1a')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
            options={
                'db_table': 'user_enterprise',
                'verbose_name_plural': '\u76d1\u6d4b\u4f01\u4e1a',
            },
        ),
        migrations.AddField(
            model_name='risknews',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskmonitor.RiskNewsPublisher', verbose_name='\u6587\u7ae0\u53d1\u5e03\u8005'),
        ),
    ]
