# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-08 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskmonitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaindustry',
            name='status',
            field=models.IntegerField(default=0, verbose_name='\u72b6\u6001'),
        )
    ]
