# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskmonitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreindustry',
            name='cycle',
            field=models.IntegerField(default=0, verbose_name='\u5468\u671f'),
        ),
    ]
