# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 01:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riskmonitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreenterprise',
            name='increment',
            field=models.IntegerField(default=0, verbose_name='\u589e\u91cf'),
        ),
        migrations.AddField(
            model_name='scoreenterprise',
            name='reducescore',
            field=models.IntegerField(default=0, verbose_name='\u6240\u51cf\u7684\u5206\u6570'),
        ),
        migrations.AddField(
            model_name='scoreenterprise',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
    ]
