# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-13 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('riskmonitor', '0002_auto_20160407_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskInspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4f5c\u8005')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='\u6807\u9898')),
                ('url', models.URLField(verbose_name='\u7f51\u7ad9\u94fe\u63a5')),
                ('content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='\u6b63\u6587')),
                ('source', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4fe1\u606f\u6765\u6e90')),
                ('pubtime', models.DateTimeField(verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('uuid', models.CharField(max_length=36)),
                ('feeling_factor', models.FloatField(default=-1, verbose_name='\u6b63\u8d1f\u9762')),
                ('reprinted', models.IntegerField(verbose_name='\u8f6c\u8f7d\u6570')),
                ('status', models.IntegerField(default=0, verbose_name='\u72b6\u6001')),
                ('qualitied', models.FloatField(verbose_name='\u5408\u683c\u7387')),
                ('create_at', models.DateTimeField(verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_at', models.DateTimeField(verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('create_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u521b\u5efa\u4eba')),
                ('sync', models.IntegerField(blank=True, null=True, verbose_name='\u540c\u6b65\u72b6\u6001')),
                ('area', models.ManyToManyField(related_name='risk_inspections', related_query_name=b'risk_inspection', to='base.Area', verbose_name='\u5730\u57df')),
                ('enterprise', models.ManyToManyField(related_name='risk_inspections', related_query_name=b'risk_inspection', to='riskmonitor.Enterprise', verbose_name='\u4f01\u4e1a')),
                ('industry', models.ManyToManyField(related_name='risk_inspections', related_query_name=b'risk_inspection', to='riskmonitor.Industry', verbose_name='\u884c\u4e1a')),
            ],
            options={
                'ordering': ['-pubtime'],
                'db_table': 'risk_inspection',
                'verbose_name_plural': '\u98ce\u9669\u62bd\u68c0',
            },
        ),
        migrations.CreateModel(
            name='RiskInspectionPublisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.URLField(verbose_name='\u7528\u6237\u5934\u50cf')),
                ('publisher', models.CharField(max_length=255, verbose_name='\u53d1\u5e03\u8005')),
                ('brief', models.CharField(max_length=255, verbose_name='\u7b80\u4ecb')),
                ('searchmode', models.IntegerField(default=0, verbose_name='\u641c\u7d22\u65b9\u5f0f')),
            ],
            options={
                'db_table': 'riskinspectionpublisher',
                'verbose_name_plural': '\u98ce\u9669\u62bd\u68c0\u53d1\u5e03\u8005',
            },
        ),
        migrations.AddField(
            model_name='riskinspection',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskmonitor.RiskInspectionPublisher', verbose_name='\u6587\u7ae0\u53d1\u5e03\u8005'),
        ),
    ]
