# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskmonitor', '0002_scoreindustry_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreindustry',
            name='increment',
            field=models.IntegerField(default=0, verbose_name='\u589e\u91cf'),
        ),
    ]
