# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskmonitor', '0003_scoreindustry_increment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoreindustry',
            name='increment',
        ),
        migrations.AddField(
            model_name='scoreindustry',
            name='addscore',
            field=models.IntegerField(default=0, verbose_name='\u6240\u9700\u52a0\u7684\u5206\u6570'),
        ),
    ]
