# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskmonitor', '0004_auto_20160329_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoreindustry',
            name='cycle',
        ),
        migrations.AddField(
            model_name='scoreindustry',
            name='increment',
            field=models.IntegerField(default=0, verbose_name='\u589e\u91cf'),
        ),
    ]
