# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riskmonitor', '0005_auto_20160413_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, verbose_name='\u5173\u952e\u8bcd')),
            ],
            options={
                'db_table': 'risk_keyword',
                'verbose_name_plural': '\u98ce\u9669\u65b0\u95fb\u5173\u952e\u8bcd',
            },
        ),
        migrations.AddField(
            model_name='risknews',
            name='risk_keyword',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='riskmonitor.RiskKeyword', verbose_name='\u98ce\u9669\u65b0\u95fb\u5173\u952e\u8bcd'),
        ),
    ]
