# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskmonitor', '0005_auto_20160329_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoreindustry',
            name='addscore',
        ),
        migrations.AddField(
            model_name='scoreindustry',
            name='reducescore',
            field=models.IntegerField(default=0, verbose_name='\u6240\u51cf\u7684\u5206\u6570'),
        ),
    ]
