# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 02:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riskmonitor', '0006_auto_20160426_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskkeyword',
            old_name='keyword',
            new_name='name',
        ),
    ]
