# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskmonitor', '0007_auto_20160427_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreenterprise',
            name='score',
            field=models.IntegerField(default=0, verbose_name='\u5206\u503c'),
        ),
        migrations.AlterField(
            model_name='scoreindustry',
            name='score',
            field=models.IntegerField(default=0, verbose_name='\u5206\u503c'),
        ),
    ]
