# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riskmonitor', '0009_auto_20160427_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskinspectionpublisher',
            old_name='publisher',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='ccc',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='locate_x',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='locate_y',
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='riskinspection',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='riskinspection',
            name='create_id',
        ),
        migrations.RemoveField(
            model_name='riskinspection',
            name='feeling_factor',
        ),
        migrations.RemoveField(
            model_name='riskinspection',
            name='reprinted',
        ),
        migrations.RemoveField(
            model_name='riskinspection',
            name='source',
        ),
        migrations.RemoveField(
            model_name='riskinspection',
            name='status',
        ),
        migrations.RemoveField(
            model_name='riskinspection',
            name='sync',
        ),
        migrations.RemoveField(
            model_name='riskinspection',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='riskinspection',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='riskinspectionpublisher',
            name='brief',
        ),
        migrations.RemoveField(
            model_name='riskinspectionpublisher',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='riskinspectionpublisher',
            name='searchmode',
        ),
        migrations.RemoveField(
            model_name='risknews',
            name='author',
        ),
        migrations.RemoveField(
            model_name='risknews',
            name='feeling_factor',
        ),
        migrations.RemoveField(
            model_name='risknews',
            name='source',
        ),
        migrations.RemoveField(
            model_name='risknews',
            name='status',
        ),
        migrations.RemoveField(
            model_name='risknews',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='risknewspublisher',
            name='brief',
        ),
        migrations.RemoveField(
            model_name='risknewspublisher',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='risknewspublisher',
            name='searchmode',
        ),
        migrations.AlterModelTable(
            name='riskinspectionpublisher',
            table='risk_inspection_publisher',
        ),
        migrations.AlterModelTable(
            name='risknewspublisher',
            table='risk_news_publisher',
        ),
    ]
