# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskmonitor', '0010_auto_20160506_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskinspection',
            name='reprinted',
            field=models.IntegerField(default=0, verbose_name='\u8f6c\u8f7d\u6570'),
        ),
    ]
