# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-18 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riskmonitor', '0012_auto_20160516_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industry',
            name='area',
        ),
    ]
