# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-19 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riskmonitor', '0013_remove_industry_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumeIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u56fd\u5bb6\u5f3a\u5236\u6027\u8981\u6c42')),
                ('close', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5bc6\u5207\u7a0b\u5ea6')),
                ('consume', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u6d89\u53ca\u7279\u5b9a\u6d88\u8d39\u7fa4\u4f53\u548c\u7279\u6b8a\u8981\u6c42')),
                ('year', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5e74\u5ea6')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskmonitor.Industry', verbose_name='\u884c\u4e1a')),
            ],
            options={
                'db_table': 'consume_index',
                'verbose_name_plural': '\u6d88\u8d39\u6307\u6807(\u7ef4)',
            },
        ),
        migrations.CreateModel(
            name='ManageIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence', models.BooleanField(default=False, verbose_name='\u5217\u5165\u8bb8\u53ef\u8bc1\u76ee\u5f55')),
                ('productauth', models.BooleanField(default=False, verbose_name='\u5217\u5165\u4ea7\u54c1\u8ba4\u8bc1\u76ee\u5f55')),
                ('policy', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4ea7\u4e1a\u653f\u7b56')),
                ('year', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5e74\u5ea6')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskmonitor.Industry', verbose_name='\u884c\u4e1a')),
            ],
            options={
                'db_table': 'manage_index',
                'verbose_name_plural': '\u7ba1\u7406\u6307\u6807(\u7ef4)',
            },
        ),
        migrations.CreateModel(
            name='MultiDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manage', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u7ba1\u7406\u7eac')),
                ('society', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u793e\u4f1a\u5f71\u54cd\u7eac')),
                ('consume', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u6c11\u751f\u76f8\u5173\u7eac')),
                ('news', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4e92\u8054\u7f51\u4fe1\u606f\u7eac')),
                ('inspection', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u62bd\u68c0\u7eac')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskmonitor.Industry', verbose_name='\u884c\u4e1a')),
            ],
            options={
                'db_table': 'multi_dimension',
                'verbose_name_plural': '\u591a\u7ef4\u8868',
            },
        ),
        migrations.CreateModel(
            name='SocietyIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u8d38\u6613\u91cf')),
                ('qualified', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u62bd\u68c0\u5408\u683c\u7387')),
                ('accident', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u6848\u4f8b\u53d1\u751f\u72b6\u51b5')),
                ('year', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5e74\u5ea6')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskmonitor.Industry', verbose_name='\u884c\u4e1a')),
            ],
            options={
                'db_table': 'society_index',
                'verbose_name_plural': '\u793e\u4f1a\u6027\u6307\u6807(\u7ef4)',
            },
        ),
    ]
