# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-20 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskmonitor', '0014_consumeindex_manageindex_multidimension_societyindex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multidimension',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='manageindex',
            name='policy',
        ),
        migrations.AddField(
            model_name='manageindex',
            name='encourage',
            field=models.BooleanField(default=0, verbose_name='\u662f\u5426\u9f13\u52b1'),
        ),
        migrations.AddField(
            model_name='manageindex',
            name='limit',
            field=models.BooleanField(default=0, verbose_name='\u662f\u5426\u9650\u5236'),
        ),
        migrations.AddField(
            model_name='manageindex',
            name='remove',
            field=models.BooleanField(default=0, verbose_name='\u662f\u5426\u6dd8\u6c70'),
        ),
        migrations.DeleteModel(
            name='MultiDimension',
        ),
    ]
