# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riskmonitor', '0016_auto_20160624_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskdata',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='origin.Area', verbose_name='\u5730\u57df'),
        ),
        migrations.AlterField(
            model_name='risknews',
            name='area',
            field=models.ManyToManyField(related_name='rareas', related_query_name=b'rarea', to='origin.Area', verbose_name='\u5730\u57df'),
        ),
        migrations.AlterField(
            model_name='userarea',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='origin.Area', verbose_name='\u5730\u57df'),
        ),
    ]
