# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskmonitor', '0017_auto_20160624_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumeindex',
            name='close',
            field=models.IntegerField(blank=True, choices=[(1, '\u4f4e'), (2, '\u4e2d'), (3, '\u9ad8')], null=True, verbose_name='\u5bc6\u5207\u7a0b\u5ea6'),
        ),
        migrations.AlterField(
            model_name='consumeindex',
            name='consume',
            field=models.IntegerField(blank=True, choices=[(0, '\u5426'), (1, '\u662f')], null=True, verbose_name='\u6d89\u53ca\u7279\u5b9a\u6d88\u8d39\u7fa4\u4f53\u548c\u7279\u6b8a\u8981\u6c42'),
        ),
        migrations.AlterField(
            model_name='consumeindex',
            name='force',
            field=models.IntegerField(blank=True, choices=[(0, '\u65e0'), (1, '\u6709')], null=True, verbose_name='\u56fd\u5bb6\u5f3a\u5236\u6027\u8981\u6c42'),
        ),
        migrations.AlterField(
            model_name='manageindex',
            name='encourage',
            field=models.IntegerField(blank=True, choices=[(0, '\u5426'), (1, '\u662f')], null=True, verbose_name='\u662f\u5426\u9f13\u52b1'),
        ),
        migrations.AlterField(
            model_name='manageindex',
            name='licence',
            field=models.IntegerField(blank=True, choices=[(0, '\u5426'), (1, '\u662f')], null=True, verbose_name='\u5217\u5165\u8bb8\u53ef\u8bc1\u76ee\u5f55'),
        ),
        migrations.AlterField(
            model_name='manageindex',
            name='limit',
            field=models.IntegerField(blank=True, choices=[(0, '\u5426'), (1, '\u662f')], null=True, verbose_name='\u662f\u5426\u9650\u5236'),
        ),
        migrations.AlterField(
            model_name='manageindex',
            name='productauth',
            field=models.IntegerField(blank=True, choices=[(0, '\u5426'), (1, '\u662f')], null=True, verbose_name='\u5217\u5165\u4ea7\u54c1\u8ba4\u8bc1\u76ee\u5f55'),
        ),
        migrations.AlterField(
            model_name='manageindex',
            name='remove',
            field=models.IntegerField(blank=True, choices=[(0, '\u5426'), (1, '\u662f')], null=True, verbose_name='\u662f\u5426\u6dd8\u6c70'),
        ),
        migrations.AlterField(
            model_name='societyindex',
            name='accident',
            field=models.IntegerField(blank=True, choices=[(1, '\u4f4e'), (2, '\u4e2d'), (3, '\u9ad8')], null=True, verbose_name='\u6848\u4f8b\u53d1\u751f\u72b6\u51b5'),
        ),
        migrations.AlterField(
            model_name='societyindex',
            name='qualified',
            field=models.IntegerField(blank=True, choices=[(1, '\u4f4e'), (2, '\u4e2d'), (3, '\u9ad8')], null=True, verbose_name='\u62bd\u68c0\u5408\u683c\u7387'),
        ),
        migrations.AlterField(
            model_name='societyindex',
            name='trade',
            field=models.IntegerField(blank=True, choices=[(1, '\u4f4e'), (2, '\u4e2d'), (3, '\u9ad8')], null=True, verbose_name='\u8d38\u6613\u91cf'),
        ),
    ]
