# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskmonitor', '0018_auto_20160711_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumeindex',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u5e74\u5ea6'),
        ),
        migrations.AlterField(
            model_name='manageindex',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u5e74\u5ea6'),
        ),
        migrations.AlterField(
            model_name='societyindex',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u5e74\u5ea6'),
        ),
    ]
