# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-02 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskmonitor', '0019_auto_20160711_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k', models.CharField(max_length=255, verbose_name='\u952e')),
                ('v', models.TextField(blank=True, verbose_name='\u503c')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'verbose_name_plural': '\u7f13\u5b58',
            },
        ),
    ]
