# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-06 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskmonitor', '0020_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u540d\u79f0')),
                ('days', models.IntegerField(verbose_name='\u95f4\u9694\u5929\u6570')),
                ('params', models.TextField(blank=True, verbose_name='\u53c2\u6570')),
            ],
            options={
                'verbose_name_plural': '\u7f13\u5b58\u914d\u7f6e',
            },
        ),
    ]
