# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-08 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0012_auto_20160711_1646'),
        ('riskmonitor', '0021_cacheconf'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaIndustry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u540d\u79f0')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='origin.Area', verbose_name='\u5730\u57df')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='origin.Industry', verbose_name='\u884c\u4e1a')),
            ],
            options={
                'verbose_name_plural': '\u5730\u57df\u884c\u4e1a',
            },
        ),
        migrations.RemoveField(
            model_name='userindustry',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='userindustry',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserIndustry',
        ),
    ]
