# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-09 12:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskmonitor', '0022_auto_20160908_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummariesScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='\u6574\u4f53\u5206\u6570')),
                ('pubtime', models.DateField(default=datetime.date.today, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name_plural': '\u6574\u4f53\u5206\u6570',
            },
        ),
    ]
