# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-03 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0013_auto_20160912_1159'),
        ('riskmonitor', '0024_internetscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumeindex',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='origin.Area', verbose_name='\u5730\u57df'),
        ),
        migrations.AddField(
            model_name='manageindex',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='origin.Area', verbose_name='\u5730\u57df'),
        ),
        migrations.AddField(
            model_name='societyindex',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='origin.Area', verbose_name='\u5730\u57df'),
        ),
    ]
