# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativePenalties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='\u6807\u9898')),
                ('url', models.URLField(verbose_name='\u7f51\u7ad9\u94fe\u63a5')),
                ('content', tinymce.models.HTMLField(blank=True, verbose_name='\u6b63\u6587')),
                ('pubtime', models.DateTimeField(verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('publisher', models.CharField(max_length=255, verbose_name='\u53d1\u5e03\u8005')),
                ('province', models.CharField(max_length=255, verbose_name='\u7701')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5e02')),
                ('district', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5730\u57df')),
                ('industry', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u884c\u4e1a')),
                ('productCategory', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4ea7\u54c1\u79cd\u7c7b')),
                ('brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5546\u6807')),
                ('caseName', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u6848\u4ef6\u540d\u79f0')),
                ('penaltyOrgan', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5904\u7f5a\u673a\u5173')),
                ('punishedName', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u88ab\u5904\u7f5a\u8005\u540d\u79f0')),
                ('punishedDistrict', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u88ab\u5904\u7f5a\u8005\u6240\u5728\u5730')),
                ('illegalBehavior', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u8fdd\u6cd5\u884c\u4e3a')),
                ('punishmentBasis', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5904\u7f5a\u4f9d\u636e')),
                ('punishmentRsult', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5904\u7f5a\u7ed3\u679c')),
            ],
            options={
                'ordering': ['-pubtime'],
                'db_table': 'administrative_penalties',
                'verbose_name_plural': '\u884c\u653f\u5904\u7f5a',
            },
        ),
    ]
