# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-05 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('origin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativePenalties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='\u6807\u9898')),
                ('url', models.URLField(verbose_name='\u7f51\u7ad9\u94fe\u63a5')),
                ('content', tinymce.models.HTMLField(blank=True, verbose_name='\u6b63\u6587')),
                ('pubtime', models.DateTimeField(blank=True, null=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('publisher', models.CharField(max_length=255, verbose_name='\u53d1\u5e03\u8005')),
                ('case_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u6848\u4ef6\u540d\u79f0')),
                ('illegal_behavior', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u8fdd\u6cd5\u884c\u4e3a')),
                ('punishment_basis', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5904\u7f5a\u4f9d\u636e')),
                ('punishment_result', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5904\u7f5a\u7ed3\u679c')),
                ('penalty_organ', models.CharField(max_length=255, verbose_name='\u5904\u7f5a\u673a\u5173')),
                ('area', models.ManyToManyField(to='origin.Area', verbose_name='\u5730\u57df')),
                ('enterprise', models.ManyToManyField(to='origin.Enterprise', verbose_name='\u5904\u7f5a\u4f01\u4e1a')),
                ('industry', models.ManyToManyField(to='origin.Industry', verbose_name='\u884c\u4e1a')),
            ],
            options={
                'ordering': ['-pubtime'],
                'db_table': 'administrative_penalties',
                'verbose_name_plural': '\u884c\u653f\u5904\u7f5a',
            },
        ),
    ]
