# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-12 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativepenalties',
            name='credit_code',
            field=models.CharField(default='', max_length=255, verbose_name='\u7edf\u4e00\u793e\u4f1a\u4fe1\u7528\u4ee3\u7801'),
        ),
    ]
