# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-12 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalty', '0002_administrativepenalties_credit_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativepenalties',
            name='area',
            field=models.ManyToManyField(blank=True, null=True, to='origin.Area', verbose_name='\u5730\u57df'),
        ),
        migrations.AlterField(
            model_name='administrativepenalties',
            name='enterprise',
            field=models.ManyToManyField(blank=True, null=True, to='origin.Enterprise', verbose_name='\u5904\u7f5a\u4f01\u4e1a'),
        ),
        migrations.AlterField(
            model_name='administrativepenalties',
            name='industry',
            field=models.ManyToManyField(blank=True, null=True, to='origin.Industry', verbose_name='\u884c\u4e1a'),
        ),
    ]
