# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riskmonitor', '0017_auto_20160624_1654'),
        ('origin', '0008_auto_20160624_1654'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='parent',
        ),
        migrations.AlterField(
            model_name='article',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='origin.Area', verbose_name='\u5730\u57df'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='origin.Area', verbose_name='\u5730\u57df'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='origin.Area', verbose_name='\u5730\u57df'),
        ),
        migrations.AlterField(
            model_name='user',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='origin.Area'),
        ),
        migrations.AlterField(
            model_name='weibo',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='origin.Area', verbose_name='\u5730\u57df'),
        ),
        migrations.AlterField(
            model_name='weixin',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='origin.Area', verbose_name='\u5730\u57df'),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
