# Generated by Django 2.0 on 2017-12-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativepenalties',
            name='publisher',
            field=models.CharField(max_length=80, verbose_name='发布者'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.CharField(blank=True, max_length=80, verbose_name='信息来源'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='name',
            field=models.CharField(max_length=25, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='source',
            field=models.CharField(max_length=80, verbose_name='信息来源'),
        ),
    ]
