# Generated by Django 3.1.4 on 2020-12-17 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='名称')),
            ],
            options={
                'verbose_name_plural': '类别表',
                'db_table': 'dyy_category',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='名称')),
            ],
            options={
                'verbose_name_plural': '导演表',
                'db_table': 'dyy_director',
            },
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='名称')),
            ],
            options={
                'verbose_name_plural': '明星表',
                'db_table': 'dyy_star',
            },
        ),
        migrations.CreateModel(
            name='VideoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='名称')),
            ],
            options={
                'verbose_name_plural': '视频类型表',
                'db_table': 'dyy_videotype',
            },
        ),
        migrations.CreateModel(
            name='VideoDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题名')),
                ('thumb', models.CharField(max_length=255, null=True, verbose_name='封面')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='原名')),
                ('alias', models.CharField(max_length=255, null=True, verbose_name='别名')),
                ('time', models.CharField(max_length=50, null=True, verbose_name='年份')),
                ('area', models.CharField(max_length=255, null=True, verbose_name='区域')),
                ('language', models.CharField(max_length=50, null=True, verbose_name='语言')),
                ('releasetime', models.CharField(max_length=50, null=True, verbose_name='上映时间')),
                ('newtime', models.CharField(max_length=50, null=True, verbose_name='更新时间')),
                ('television', models.CharField(max_length=50, null=True, verbose_name='电视台')),
                ('lianzaijs', models.CharField(max_length=255, null=True, verbose_name='连载集数')),
                ('introduction', models.CharField(max_length=2000, null=True, verbose_name='简介')),
                ('heat', models.CharField(max_length=255, null=True, verbose_name='热度')),
                ('score', models.CharField(max_length=255, null=True, verbose_name='评分')),
                ('source', models.CharField(max_length=255, verbose_name='来源')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('is_new', models.IntegerField(default=0, verbose_name='是否更新状态')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dyy.director', verbose_name='导演表')),
                ('stars', models.ManyToManyField(to='dyy.Star')),
                ('videotypes', models.ManyToManyField(to='dyy.VideoType')),
            ],
            options={
                'verbose_name_plural': '视频详情表',
                'db_table': 'dyy_videodetails',
            },
        ),
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='名字')),
                ('source', models.CharField(max_length=255, null=True, verbose_name='视频源')),
                ('url', models.CharField(max_length=255, null=True, verbose_name='播放地址')),
                ('videodetails', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dyy.videodetails', verbose_name='视频详情表')),
            ],
            options={
                'verbose_name_plural': '视频源表',
                'db_table': 'dyy_videocontent',
            },
        ),
    ]
