# Generated by Django 3.1.4 on 2020-12-17 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dyy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodetails',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dyy.category', verbose_name='影视类型'),
        ),
    ]
