# Generated by Django 3.1.4 on 2020-12-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dyy', '0002_videodetails_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodetails',
            name='source',
            field=models.CharField(max_length=255, null=True, verbose_name='来源'),
        ),
    ]
