# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('origin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=255, verbose_name='uuid')),
                ('riskword', models.TextField(default='', max_length=255, verbose_name='\u98ce\u9669\u8bed\u6599\u8bcd')),
                ('invalidword', models.TextField(default='', max_length=255, verbose_name='\u65e0\u6548\u8bcd')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='origin.Industry', verbose_name='\u884c\u4e1a')),
            ],
            options={
                'verbose_name_plural': '\u8bed\u6599\u5e93',
            },
        ),
    ]
