# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-31 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('riskmonitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=255, verbose_name='uuid')),
                ('riskword', models.TextField(blank=True, max_length=255, null=True, verbose_name='\u98ce\u9669\u8bed\u6599\u8bcd')),
                ('invalidword', models.TextField(blank=True, max_length=255, null=True, verbose_name='\u65e0\u6548\u8bcd')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riskmonitor.Industry', verbose_name='\u884c\u4e1a')),
            ],
            options={
                'db_table': 'corpus',
                'verbose_name_plural': '\u8bed\u6599\u5e93',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='\u6807\u9898')),
            ],
            options={
                'db_table': 'event',
                'verbose_name_plural': '\u805a\u7c7b\u4e8b\u4ef6',
            },
        ),
    ]
