# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='origin.Industry', verbose_name='\u884c\u4e1a'),
        ),
    ]
