# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riskmonitor', '0001_initial'),
        ('corpus', '0002_auto_20160323_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpus',
            name='user_industry',
        ),
        migrations.AddField(
            model_name='corpus',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riskmonitor.Industry', verbose_name='\u884c\u4e1a'),
        ),
    ]
