# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-16 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('riskmonitor', '0012_auto_20160516_0905'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4f5c\u8005')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='\u6807\u9898')),
                ('url', models.URLField(verbose_name='\u7f51\u7ad9\u94fe\u63a5')),
                ('content', models.TextField(blank=True, null=True, verbose_name='\u6b63\u6587')),
                ('pubtime', models.DateTimeField(verbose_name='\u53d1\u5e03\u65f6\u95f4')),
                ('qualitied', models.FloatField(verbose_name='\u5408\u683c\u7387')),
                ('reprinted', models.IntegerField(default=0, verbose_name='\u8f6c\u8f7d\u6570')),
                ('area', models.ManyToManyField(related_name='inspections', related_query_name=b'inspection', to='base.Area', verbose_name='\u5730\u57df')),
                ('enterprise', models.ManyToManyField(related_name='inspections', related_query_name=b'inspection', to='riskmonitor.Enterprise', verbose_name='\u4f01\u4e1a')),
                ('industry', models.ManyToManyField(related_name='inspections', related_query_name=b'inspection', to='riskmonitor.Industry', verbose_name='\u884c\u4e1a')),
            ],
            options={
                'ordering': ['-pubtime'],
                'db_table': 'origin_inspection',
                'verbose_name_plural': '\u98ce\u9669\u62bd\u68c0',
            },
        ),
        migrations.CreateModel(
            name='InspectionPublisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u53d1\u5e03\u8005')),
            ],
            options={
                'db_table': 'origin_inspection_publisher',
                'verbose_name_plural': '\u62bd\u68c0\u53d1\u5e03\u8005',
            },
        ),
        migrations.AddField(
            model_name='inspection',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='origin.InspectionPublisher', verbose_name='\u6587\u7ae0\u53d1\u5e03\u8005'),
        ),
    ]
