# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-16 03:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='author',
        ),
    ]
