# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-16 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0002_remove_inspection_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectionpublisher',
            options={'verbose_name_plural': '\u62bd\u68c0\u5355\u4f4d'},
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='reprinted',
        ),
        migrations.AddField(
            model_name='inspection',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5546\u6807'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='samtime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u62bd\u68c0\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='unitem',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4e0d\u5408\u683c\u9879'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='area',
            field=models.ManyToManyField(related_name='inspections', related_query_name=b'inspection', to='base.Area', verbose_name='\u62bd\u68c0\u5730\u57df'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='origin.InspectionPublisher', verbose_name='\u62bd\u68c0\u5355\u4f4d'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='pubtime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u53d1\u5e03\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='qualitied',
            field=models.FloatField(blank=True, null=True, verbose_name='\u5408\u683c\u7387'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u6807\u9898'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='\u7f51\u7ad9\u94fe\u63a5'),
        ),
        migrations.AlterField(
            model_name='inspectionpublisher',
            name='name',
            field=models.CharField(max_length=255, verbose_name='\u62bd\u68c0\u5355\u4f4d'),
        ),
    ]
