# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-17 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0003_auto_20160516_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='unitem',
            field=models.TextField(blank=True, null=True, verbose_name='\u4e0d\u5408\u683c\u9879'),
        ),
    ]
