# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-19 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0004_auto_20160517_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='samtime',
        ),
        migrations.AddField(
            model_name='inspection',
            name='product',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4ea7\u54c1\u79cd\u7c7b'),
        ),
    ]
