# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('origin', '0005_auto_20160519_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u4f01\u4e1a\u540d')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Area', verbose_name='\u5730\u57df')),
            ],
            options={
                'db_table': 'enterprise',
                'verbose_name_plural': '\u4f01\u4e1a',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u540d\u79f0')),
                ('level', models.BigIntegerField(verbose_name='\u884c\u4e1a\u5c42\u7ea7')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='origin.Industry', verbose_name='\u4e0a\u4e00\u7ea7')),
            ],
            options={
                'db_table': 'industry',
                'verbose_name_plural': '\u884c\u4e1a',
            },
        ),
        migrations.AlterField(
            model_name='inspection',
            name='enterprise',
            field=models.ManyToManyField(related_name='inspections', related_query_name=b'inspection', to='origin.Enterprise', verbose_name='\u4f01\u4e1a'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='industry',
            field=models.ManyToManyField(related_name='inspections', related_query_name=b'inspection', to='origin.Industry', verbose_name='\u884c\u4e1a'),
        ),
    ]
