# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0006_auto_20160624_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='enterprise',
        ),
        migrations.AddField(
            model_name='inspection',
            name='enterprise_qualified',
            field=models.ManyToManyField(related_name='enterprises_qualified', related_query_name=b'enterprise_qualified', to='origin.Enterprise', verbose_name='\u5408\u683c\u4f01\u4e1a'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='enterprise_unqualified',
            field=models.ManyToManyField(related_name='enterprises_unqualified', related_query_name=b'enterprise_unqualified', to='origin.Enterprise', verbose_name='\u4e0d\u5408\u683c\u4f01\u4e1a'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='area',
            field=models.ManyToManyField(related_name='areas', related_query_name=b'area', to='base.Area', verbose_name='\u62bd\u68c0\u5730\u57df'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='industry',
            field=models.ManyToManyField(related_name='industries', related_query_name=b'industry', to='origin.Industry', verbose_name='\u884c\u4e1a'),
        ),
    ]
