# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0007_auto_20160624_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u540d\u79f0')),
                ('level', models.BigIntegerField(verbose_name='\u7b49\u7ea7')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='origin.Area', verbose_name='\u4e0a\u4e00\u7ea7')),
            ],
            options={
                'db_table': 'area',
                'verbose_name_plural': '\u5730\u57df',
            },
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='origin.Area', verbose_name='\u5730\u57df'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='area',
            field=models.ManyToManyField(related_name='areas', related_query_name=b'area', to='origin.Area', verbose_name='\u62bd\u68c0\u5730\u57df'),
        ),
    ]
