# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0010_auto_20160628_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='industry',
            field=models.ManyToManyField(to='origin.Industry', verbose_name='\u884c\u4e1a'),
        ),
    ]
