# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0011_auto_20160628_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='enterprise_qualified',
            field=models.ManyToManyField(blank=True, related_name='enterprises_qualified', related_query_name=b'enterprise_qualified', to='origin.Enterprise', verbose_name='\u5408\u683c\u4f01\u4e1a'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='enterprise_unqualified',
            field=models.ManyToManyField(blank=True, related_name='enterprises_unqualified', related_query_name=b'enterprise_unqualified', to='origin.Enterprise', verbose_name='\u4e0d\u5408\u683c\u4f01\u4e1a'),
        ),
    ]
