# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-12 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0012_auto_20160711_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='issues',
            field=models.CharField(max_length=255, null=True, verbose_name='\u98ce\u9669\u4e8b\u9879'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='product_name',
            field=models.CharField(max_length=255, null=True, verbose_name='\u98ce\u9669\u4ea7\u54c1\u540d\u79f0'),
        ),
    ]
