# Generated by Django 2.0.3 on 2018-04-02 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DMLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='网站名')),
                ('link', models.URLField(verbose_name='网站链接')),
                ('kwords', models.CharField(max_length=255, verbose_name='关键词')),
                ('fwords', models.CharField(max_length=255, verbose_name='过滤词')),
                ('remarks', models.CharField(max_length=255, verbose_name='备注信息')),
                ('create_at', models.DateTimeField(verbose_name='创建时间')),
                ('update_at', models.DateTimeField(verbose_name='更新时间')),
                ('status', models.IntegerField(verbose_name='状态')),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name_plural': '指定监测-链接',
            },
        ),
    ]
