# Generated by Django 2.0.3 on 2018-03-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AddField(
            model_name='category',
            name='guid',
            field=models.CharField(default='', max_length=4, primary_key=True, serialize=False, verbose_name='主键'),
            preserve_default=False,
        ),
    ]
