# Generated by Django 2.0.3 on 2018-03-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20180328_1058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='articlecategory',
            name='category_id',
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='category',
            field=models.CharField(choices=[('0001', '质监热点'), ('0002', '风险快讯'), ('0003', '业务信息')], default='', max_length=4, verbose_name='信息类别'),
            preserve_default=False,
        ),
    ]
