# Generated by Django 2.0.3 on 2018-04-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_corpus'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='status',
            field=models.IntegerField(default=0, verbose_name='状态'),
        ),
    ]
