# Generated by Django 2.0.3 on 2018-03-28 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_auto_20180328_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Area', verbose_name='地域')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '用户地域',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='guid',
            field=models.CharField(editable=False, max_length=32, primary_key=True, serialize=False, verbose_name='主键'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='guid',
            field=models.CharField(editable=False, max_length=32, primary_key=True, serialize=False, verbose_name='主键'),
        ),
    ]
