# Generated by Django 2.0.3 on 2018-03-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20180328_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(max_length=32, verbose_name='文章GUID')),
                ('area_id', models.IntegerField(verbose_name='地域ID')),
            ],
            options={
                'verbose_name_plural': '文章地域',
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='area_id',
        ),
    ]
