# Generated by Django 2.0.3 on 2018-04-24 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_inspection_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspectionenterprise',
            old_name='enterpise_id',
            new_name='enterprise_id',
        ),
    ]
