# Generated by Django 2.0.3 on 2018-05-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20180424_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publisher',
            field=models.CharField(blank=True, max_length=80, verbose_name='发布者'),
        ),
    ]
