# Generated by Django 2.0.3 on 2018-03-28 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20180328_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='类别ID')),
                ('name', models.CharField(max_length=10, verbose_name='名称')),
                ('level', models.IntegerField(verbose_name='等级')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Category', verbose_name='上一级')),
            ],
            options={
                'verbose_name_plural': '文章分类',
            },
        ),
        migrations.RemoveField(
            model_name='articlecategory',
            name='category',
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='category_id',
            field=models.CharField(default='', max_length=5, verbose_name='信息类别'),
            preserve_default=False,
        ),
    ]
