# Generated by Django 2.0.3 on 2018-03-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20180328_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '类别'},
        ),
        migrations.AddField(
            model_name='inspection',
            name='category',
            field=models.CharField(default='', max_length=32, verbose_name='抽查类别'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inspection',
            name='pubtime',
            field=models.DateField(default='1990-09-09', verbose_name='发布时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inspection',
            name='unitem',
            field=models.CharField(max_length=255, verbose_name='不合格项'),
        ),
    ]
