# Generated by Django 2.0.5 on 2018-06-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20180524_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cccindustry',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='行业描述'),
        ),
    ]
