# Generated by Django 2.0.5 on 2018-07-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20180621_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseindustry',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='行业描述'),
        ),
    ]
