# Generated by Django 2.0.5 on 2018-07-04 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20180704_1112'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LicenseIndustry',
            new_name='LicenceIndustry',
        ),
        migrations.RenameField(
            model_name='aliasindustry',
            old_name='license_id',
            new_name='licence_id',
        ),
    ]
