# Generated by Django 2.0.5 on 2018-07-04 16:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_consumerindustry'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorIndustry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='行业编号')),
                ('name', models.CharField(max_length=100, verbose_name='行业名称')),
                ('level', models.IntegerField(verbose_name='行业等级')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='行业描述')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.MajorIndustry', verbose_name='上一级')),
            ],
            options={
                'verbose_name_plural': '重点产品目录',
            },
        ),
    ]
