# Generated by Django 2.0.5 on 2018-07-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_majorindustry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorindustry',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='行业编号'),
        ),
    ]
