# Generated by Django 2.0.5 on 2018-07-09 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20180706_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorindustry',
            name='ccc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.CCCIndustry', verbose_name='CCC'),
        ),
        migrations.AddField(
            model_name='majorindustry',
            name='licence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.LicenceIndustry', verbose_name='许可证'),
        ),
    ]
