# Generated by Django 2.0.5 on 2018-07-11 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20180709_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPCIndustry',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='行业编号')),
                ('name', models.CharField(max_length=100, verbose_name='行业名称')),
                ('level', models.IntegerField(verbose_name='行业等级')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='行业描述')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.CPCIndustry', verbose_name='上一级')),
            ],
            options={
                'verbose_name_plural': '产品总分类(CPC)',
            },
        ),
    ]
