# Generated by Django 2.0.7 on 2018-07-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_cpcindustry'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='产品名称'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='industry_id',
            field=models.IntegerField(verbose_name='产品类别'),
        ),
    ]
