# Generated by Django 2.0.7 on 2018-07-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20180719_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='inspect_patch',
            field=models.IntegerField(default=0, verbose_name='抽查批次'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='qualitied_patch',
            field=models.IntegerField(default=0, verbose_name='合格批次'),
        ),
        migrations.AlterField(
            model_name='inspectionenterprise',
            name='enterprise_id',
            field=models.IntegerField(verbose_name='企业ID'),
        ),
    ]
