# Generated by Django 2.0.7 on 2018-07-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20180731_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='unqualitied_patch',
            field=models.IntegerField(default=0, verbose_name='不合格批次'),
        ),
    ]
