# Generated by Django 2.0.7 on 2018-08-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_inspection_unqualitied_patch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpus',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='corpus',
            name='invalidword',
        ),
        migrations.AddField(
            model_name='corpus',
            name='industry_id',
            field=models.IntegerField(default=0, verbose_name='产品类别'),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='riskword',
            field=models.CharField(default=0, max_length=255, verbose_name='风险语料词'),
        ),
    ]
