# Generated by Django 2.0.7 on 2018-09-07 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20180906_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='invalid_keyword',
        ),
        migrations.RemoveField(
            model_name='article',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='article',
            name='risk_keyword',
        ),
    ]
