# Generated by Django 2.0.7 on 2018-09-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20180907_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='corpus_id',
            field=models.IntegerField(default=0, verbose_name='语料词编号'),
        ),
    ]
