# Generated by Django 2.0.7 on 2018-10-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_article_corpus_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='status',
            field=models.IntegerField(default=1, verbose_name='状态'),
        ),
    ]
