# Generated by Django 2.0.7 on 2018-10-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_enterprise_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='产品名称')),
                ('industry_id', models.IntegerField(verbose_name='产品行业编号')),
            ],
            options={
                'verbose_name_plural': '行业产品',
            },
        ),
    ]
