# Generated by Django 2.0.7 on 2018-10-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_industryproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(default='None', max_length=32, verbose_name='GUID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('url', models.URLField(blank=True, null=True, verbose_name='网站链接')),
                ('pubtime', models.DateField(verbose_name='发布时间')),
                ('source', models.CharField(max_length=80, verbose_name='信息来源')),
                ('qualitied', models.FloatField(default=1.0, verbose_name='合格率')),
                ('unqualitied_patch', models.IntegerField(default=0, verbose_name='不合格批次')),
                ('qualitied_patch', models.IntegerField(default=0, verbose_name='合格批次')),
                ('inspect_patch', models.IntegerField(default=0, verbose_name='抽查批次')),
                ('category', models.CharField(max_length=32, verbose_name='抽查类别')),
                ('level', models.CharField(max_length=2, verbose_name='检验等级')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('industry_id', models.IntegerField(verbose_name='产品类别')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='产品名称')),
                ('area_id', models.IntegerField(verbose_name='地域ID')),
            ],
            options={
                'verbose_name_plural': '抽检信息',
                'ordering': ['-pubtime'],
            },
        ),
    ]
