# Generated by Django 2.0.7 on 2018-10-30 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_inspection2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inspection',
        ),
    ]
