# Generated by Django 2.0.7 on 2018-10-30 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_delete_inspection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inspection2',
            new_name='Inspection',
        ),
    ]
