# Generated by Django 2.0.7 on 2018-10-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_auto_20181030_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='origin_product',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='导入产品名'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='guid',
            field=models.CharField(default=None, max_length=32, verbose_name='GUID'),
        ),
    ]
