# Generated by Django 2.0.7 on 2018-11-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_auto_20181030_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='guid',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='GUID'),
        ),
    ]
