# Generated by Django 2.0.7 on 2018-11-19 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0031_auto_20181101_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('level', models.IntegerField(verbose_name='等级')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Nav', verbose_name='上一级')),
            ],
            options={
                'verbose_name_plural': '导航栏',
            },
        ),
        migrations.CreateModel(
            name='UserNav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Nav', verbose_name='导航')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '用户导航栏',
            },
        ),
    ]
