# Generated by Django 2.0.7 on 2018-11-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_nav_usernav'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav',
            name='href',
            field=models.CharField(default=0, max_length=50, verbose_name='链接'),
        ),
    ]
