# Generated by Django 2.0.7 on 2018-11-28 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_nav_href'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
