# Generated by Django 2.0.7 on 2018-11-29 02:28

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('photo', models.ImageField(upload_to='photos', verbose_name='封面')),
                ('content', tinymce.models.HTMLField(verbose_name='内容')),
                ('pubtime', models.DateField(default=datetime.date.today, verbose_name='发布时间')),
                ('tag', models.CharField(default='', max_length=255, verbose_name='标签')),
                ('views', models.IntegerField(default=0, verbose_name='浏览次数')),
            ],
            options={
                'verbose_name_plural': '公司动态',
            },
        ),
    ]
