# Generated by Django 2.0.7 on 2018-11-29 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
