# Generated by Django 2.1.4 on 2018-12-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_delete_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav',
            name='icon',
            field=models.CharField(default='', max_length=50, verbose_name='图标'),
        ),
        migrations.AddField(
            model_name='nav',
            name='index',
            field=models.IntegerField(default=0, verbose_name='索引'),
        ),
    ]
