# Generated by Django 2.1.3 on 2018-12-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus_categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(default=0, max_length=255, verbose_name='关键词语料词')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('category_id', models.IntegerField(default=0, verbose_name='信息类别')),
            ],
            options={
                'verbose_name_plural': '语料库-信息类别',
            },
        ),
    ]
