# Generated by Django 2.1.4 on 2018-12-20 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_auto_20181220_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=50, verbose_name='单位')),
                ('year', models.CharField(max_length=50, verbose_name='年份')),
                ('period', models.CharField(max_length=50, verbose_name='期数')),
                ('news_type', models.CharField(max_length=50, verbose_name='类型')),
                ('publisher', models.CharField(max_length=50, verbose_name='发布者')),
                ('pubtime', models.DateField(default=datetime.date.today, verbose_name='发布时间')),
                ('file', models.FileField(upload_to='upload/%Y/%m/%d', verbose_name='文件')),
            ],
            options={
                'verbose_name_plural': '舆情报告',
            },
        ),
    ]
