# Generated by Django 2.1.4 on 2018-12-20 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_newsreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsReport',
        ),
    ]
