# Generated by Django 2.1.3 on 2018-12-19 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_auto_20181219_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corpus_categories',
            old_name='keywords',
            new_name='keyword',
        ),
    ]
