# Generated by Django 2.1.4 on 2018-12-20 10:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('base', '0039_delete_newsreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50, verbose_name='年份')),
                ('period', models.CharField(max_length=50, verbose_name='期数')),
                ('news_type', models.CharField(max_length=50, verbose_name='类型')),
                ('publisher', models.CharField(max_length=50, verbose_name='发布者')),
                ('pubtime', models.DateField(default=datetime.date.today, verbose_name='发布时间')),
                ('file', models.FileField(upload_to='upload/%Y/%m/%d', verbose_name='文件')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='单位')),
            ],
            options={
                'verbose_name_plural': '舆情报告',
            },
        ),
    ]
