# Generated by Django 2.1.3 on 2018-12-27 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_newsreport'),
        ('base', '0039_auto_20181219_1722'),
    ]

    operations = [
    ]
