# Generated by Django 2.1.4 on 2018-12-24 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_auto_20181219_1722'),
        ('base', '0040_newsreport'),
    ]

    operations = [
    ]
