# Generated by Django 2.1.4 on 2018-12-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_merge_20181224_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsreport',
            name='period',
            field=models.IntegerField(verbose_name='期数'),
        ),
        migrations.AlterField(
            model_name='newsreport',
            name='year',
            field=models.IntegerField(verbose_name='年份'),
        ),
    ]
