# Generated by Django 2.1.3 on 2019-01-03 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_auto_20181224_1533'),
        ('base', '0042_corpus_categories_industry_id'),
    ]

    operations = [
    ]
