# Generated by Django 2.1.3 on 2019-01-03 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_merge_20190103_1006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Corpus',
        ),
    ]
