# Generated by Django 2.1.3 on 2019-01-03 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_delete_corpus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Corpus_categories',
            new_name='CorpusCategories',
        ),
    ]
