# Generated by Django 2.1.4 on 2019-01-07 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_auto_20190103_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='标题')),
                ('url', models.URLField(verbose_name='网站链接')),
                ('pubtime', models.DateTimeField(verbose_name='发布时间')),
                ('source', models.CharField(blank=True, max_length=80, verbose_name='信息来源')),
                ('score', models.IntegerField(default=0, verbose_name='风险程度')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('areas', models.ManyToManyField(to='base.Area')),
                ('categories', models.ManyToManyField(to='base.Category')),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.CorpusCategories', verbose_name='语料词')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.MajorIndustry', verbose_name='产品类别')),
            ],
            options={
                'verbose_name_plural': '文章',
                'ordering': ['-pubtime'],
            },
        ),
    ]
