# Generated by Django 2.1.4 on 2019-01-07 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_auto_20190103_1016'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InspectionEnterprise',
            new_name='InspectionEnterprise2',
        ),
    ]
