# Generated by Django 2.1.4 on 2019-01-07 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_auto_20190107_1042'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InspectionEnterprise2',
            new_name='InspectionEnterprise',
        ),
    ]
