# Generated by Django 2.1.4 on 2019-01-07 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_article2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article2',
            name='corpus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.CorpusCategories', verbose_name='语料词'),
        ),
        migrations.AlterField(
            model_name='article2',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.MajorIndustry', verbose_name='产品类别'),
        ),
    ]
