# Generated by Django 2.1.4 on 2019-01-07 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_auto_20190107_1643'),
        ('base', '0047_auto_20190107_1651'),
    ]

    operations = [
    ]
