# Generated by Django 2.1.4 on 2019-01-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_merge_20190107_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='corpus_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='语料词编号'),
        ),
        migrations.AlterField(
            model_name='article',
            name='industry_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='产品类别'),
        ),
    ]
