# Generated by Django 2.1.4 on 2019-01-14 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_auto_20190107_1658'),
        ('base', '0046_corpuscategories_user'),
    ]

    operations = [
    ]
