# Generated by Django 2.1.4 on 2019-01-14 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_inspection2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection2',
            name='area',
        ),
        migrations.RemoveField(
            model_name='inspection2',
            name='enterprises',
        ),
        migrations.RemoveField(
            model_name='inspection2',
            name='industry',
        ),
        migrations.DeleteModel(
            name='Inspection2',
        ),
    ]
