# Generated by Django 2.1.4 on 2019-01-16 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_auto_20190115_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('unitem', models.CharField(max_length=255, verbose_name='不合格项')),
                ('status', models.IntegerField(choices=[('1', '已审核'), ('0', '未审核')], default=0, verbose_name='状态')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Area', verbose_name='地域')),
            ],
            options={
                'verbose_name_plural': '企业',
            },
        ),
    ]
