# Generated by Django 2.1.4 on 2019-01-17 10:12

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_enterprise2'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=255, verbose_name='版本号')),
                ('content', tinymce.models.HTMLField(verbose_name='内容')),
                ('pubtime', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name_plural': '版本记录',
                'ordering': ['-pubtime'],
            },
        ),
    ]
