# Generated by Django 2.1.5 on 2019-01-21 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0060_article2_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inspection2',
            new_name='Inspection',
        ),
        migrations.RemoveField(
            model_name='article2',
            name='areas',
        ),
        migrations.RemoveField(
            model_name='article2',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='article2',
            name='corpus',
        ),
        migrations.RemoveField(
            model_name='article2',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='article2',
            name='user',
        ),
        migrations.DeleteModel(
            name='ArticleArea',
        ),
        migrations.DeleteModel(
            name='ArticleCategory',
        ),
        migrations.RemoveField(
            model_name='article',
            name='corpus_id',
        ),
        migrations.RemoveField(
            model_name='article',
            name='guid',
        ),
        migrations.RemoveField(
            model_name='article',
            name='industry_id',
        ),
        migrations.AddField(
            model_name='article',
            name='areas',
            field=models.ManyToManyField(to='base.Area'),
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(to='base.Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='corpus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.CorpusCategories', verbose_name='语料词'),
        ),
        migrations.AddField(
            model_name='article',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.MajorIndustry', verbose_name='产品类别'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.DeleteModel(
            name='Article2',
        ),
    ]
