# Generated by Django 2.1.5 on 2019-01-21 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_versionrecord'),
        ('base', '0061_auto_20190121_1053'),
    ]

    operations = [
    ]
