# Generated by Django 2.1.5 on 2019-01-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_merge_20190121_1622'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enterprise',
        ),
        migrations.AlterField(
            model_name='inspection',
            name='enterprises',
            field=models.ManyToManyField(to='base.Enterprise2'),
        ),
    ]
