# Generated by Django 2.1.5 on 2019-01-21 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_auto_20190121_1623'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enterprise2',
            new_name='Enterprise',
        ),
    ]
