# Generated by Django 2.1.4 on 2019-01-24 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_auto_20190121_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorindustry',
            name='consumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.ConsumerIndustry', verbose_name='消费品'),
        ),
        migrations.AlterField(
            model_name='majorindustry',
            name='ccc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.CCCIndustry', verbose_name='强制认证'),
        ),
    ]
