# Generated by Django 2.1.3 on 2019-02-15 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_auto_20190124_1041'),
        ('base', '0065_auto_20190123_1530'),
    ]

    operations = [
    ]
