# Generated by Django 2.1.3 on 2019-02-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0066_merge_20190215_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpuscategories',
            name='startTime',
            field=models.DateField(null=True, verbose_name='开始时间'),
        ),
        migrations.AddField(
            model_name='corpuscategories',
            name='stopTime',
            field=models.DateField(null=True, verbose_name='结束时间'),
        ),
    ]
