# Generated by Django 2.1.3 on 2019-02-25 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_auto_20190215_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskHarm',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='定义')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.RiskHarm', verbose_name='上一级')),
            ],
            options={
                'verbose_name_plural': '风险伤害',
            },
        ),
    ]
