# Generated by Django 2.1.3 on 2019-02-25 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_riskharm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='定义')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Harm', verbose_name='上一级')),
            ],
            options={
                'verbose_name_plural': '风险伤害',
            },
        ),
        migrations.RemoveField(
            model_name='riskharm',
            name='parent',
        ),
        migrations.DeleteModel(
            name='RiskHarm',
        ),
    ]
