# Generated by Django 2.1.7 on 2019-02-25 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_govreports'),
    ]

    operations = [
        migrations.RenameField(
            model_name='govreports',
            old_name='abstract',
            new_name='year',
        ),
    ]
