# Generated by Django 2.1.3 on 2019-03-01 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0070_article_harms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Harm',
            new_name='HarmIndicator',
        ),
        migrations.RemoveField(
            model_name='article',
            name='harms',
        ),
    ]
