# Generated by Django 2.1.3 on 2019-03-05 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0073_auto_20190304_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harm',
            name='harmpeple',
        ),
        migrations.AddField(
            model_name='harmpeople',
            name='harm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Harm', verbose_name='风险伤害'),
        ),
    ]
