# Generated by Django 2.1.3 on 2019-03-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0074_auto_20190305_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harmpeople',
            name='age',
            field=models.IntegerField(null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='harmpeople',
            name='sex',
            field=models.IntegerField(null=True, verbose_name='性别'),
        ),
    ]
