# Generated by Django 2.1.7 on 2019-03-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0074_auto_20190301_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='abc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=255, verbose_name='版本号')),
            ],
            options={
                'verbose_name_plural': '版本记录',
            },
        ),
    ]
