# Generated by Django 2.1.7 on 2019-03-01 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0075_abc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='abc',
        ),
    ]
