# Generated by Django 2.1.3 on 2019-03-18 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0077_merge_20190311_1010'),
        ('base', '0078_auto_20190315_1021'),
    ]

    operations = [
    ]
