# Generated by Django 2.1.5 on 2019-03-18 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0078_auto_20190315_1021'),
        ('base', '0077_merge_20190311_1010'),
    ]

    operations = [
    ]
