# Generated by Django 2.1.3 on 2019-03-18 07:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_merge_20190318_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='名称')),
                ('socialHarm', models.CharField(max_length=50, verbose_name='社会危害程度')),
                ('scope', models.CharField(max_length=50, verbose_name='影响范围')),
                ('grading', models.CharField(max_length=50, verbose_name='分级')),
                ('pubtime', models.DateField(default=datetime.date.today, verbose_name='发布时间')),
                ('desc', models.TextField(null=True, verbose_name='事件总结')),
            ],
            options={
                'verbose_name_plural': '事件分析',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='sentiment',
            field=models.IntegerField(null=True, verbose_name='情感属性'),
        ),
        migrations.AddField(
            model_name='events',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Article', verbose_name='文章'),
        ),
    ]
