# Generated by Django 2.1.3 on 2019-03-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0080_auto_20190318_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='article',
        ),
        migrations.AddField(
            model_name='events',
            name='articles',
            field=models.ManyToManyField(to='base.Article'),
        ),
    ]
