# Generated by Django 2.1.3 on 2019-03-21 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0081_auto_20190320_1023'),
        ('base', '0079_merge_20190318_1458'),
    ]

    operations = [
    ]
