# Generated by Django 2.1.3 on 2019-03-21 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0082_merge_20190321_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='关键词名')),
                ('articles', models.ManyToManyField(to='base.Article')),
                ('events', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Events', verbose_name='事件')),
            ],
        ),
    ]
