# Generated by Django 2.1.5 on 2019-03-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0083_eventskeyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='类别ID'),
        ),
    ]
