# Generated by Django 2.1.5 on 2019-04-01 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0084_auto_20190328_1538'),
        ('base', '0086_auto_20190328_1518'),
    ]

    operations = [
    ]
