# Generated by Django 2.1.5 on 2019-04-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0087_merge_20190401_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav',
            name='nav_type',
            field=models.IntegerField(default=0, verbose_name='导航类型'),
        ),
    ]
