# Generated by Django 2.1.5 on 2019-04-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0089_userinfo_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='theme',
            field=models.CharField(default='', max_length=50, verbose_name='主题'),
        ),
    ]
