# Generated by Django 2.1.5 on 2019-04-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0090_auto_20190402_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='logo',
            field=models.TextField(default='', verbose_name='logo'),
        ),
    ]
