# Generated by Django 2.1.5 on 2019-04-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0091_auto_20190402_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='logo',
            field=models.CharField(default='', max_length=50, verbose_name='logo'),
        ),
    ]
