# Generated by Django 2.2 on 2019-04-16 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0093_nav_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nav',
            name='nav_type',
        ),
    ]
