# Generated by Django 2.1.3 on 2019-04-16 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0094_keywordsstatistical_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordsstatistical',
            name='events',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Events', verbose_name='事件'),
        ),
    ]
