# Generated by Django 2.2 on 2019-04-23 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0095_nav_nav_type'),
        ('base', '0095_auto_20190416_1542'),
    ]

    operations = [
    ]
