# Generated by Django 2.1.3 on 2019-04-29 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0095_auto_20190416_1542'),
        ('base', '0095_nav_nav_type'),
    ]

    operations = [
    ]
