# Generated by Django 2.1.3 on 2019-04-29 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0096_merge_20190429_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertsView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('portrait', models.ImageField(upload_to='', verbose_name='头像')),
                ('articles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Article', verbose_name='文章-专家视点')),
            ],
            options={
                'verbose_name_plural': '专家视点',
            },
        ),
    ]
