# Generated by Django 2.2 on 2019-04-23 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0096_merge_20190423_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomCheckTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='任务名称')),
            ],
            options={
                'verbose_name_plural': '随机抽查任务',
                'db_table': 'random_check_task',
            },
        ),
        migrations.CreateModel(
            name='RandomCheckEnterpriseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='产品名称')),
                ('enterprise_name', models.CharField(max_length=255, verbose_name='生产企业名称')),
                ('enterprise_address', models.CharField(max_length=255, verbose_name='生产企业地址')),
                ('contacts', models.CharField(max_length=50, verbose_name='联系人')),
                ('phone', models.CharField(max_length=50, verbose_name='联系电话')),
                ('area', models.CharField(max_length=50, verbose_name='所属区')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.RandomCheckTask', verbose_name='任务编号')),
            ],
            options={
                'verbose_name_plural': '随机抽查企业名单',
                'db_table': 'random_check_enterprise_list',
            },
        ),
    ]
