# Generated by Django 2.2 on 2019-04-23 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0097_randomcheckenterpriselist_randomchecktask'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='randomcheckenterpriselist',
            table='base_random_check_enterprise_list',
        ),
        migrations.AlterModelTable(
            name='randomchecktask',
            table='base_random_check_task',
        ),
    ]
