# Generated by Django 2.2 on 2019-04-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0098_auto_20190423_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomcheckenterpriselist',
            name='status',
            field=models.IntegerField(default=0, verbose_name='企业状态'),
        ),
        migrations.AddField(
            model_name='randomchecktask',
            name='check_agency',
            field=models.CharField(default='', max_length=255, verbose_name='检验机构'),
        ),
        migrations.AddField(
            model_name='randomchecktask',
            name='delegate',
            field=models.CharField(default='', max_length=255, verbose_name='委托单位'),
        ),
        migrations.AddField(
            model_name='randomchecktask',
            name='perform_number',
            field=models.CharField(default='', max_length=255, verbose_name='执行文号'),
        ),
    ]
