# Generated by Django 2.2 on 2019-04-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0099_auto_20190423_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomchecktask',
            name='enterprise_number',
            field=models.IntegerField(default=0, verbose_name='抽检企业数'),
        ),
    ]
