# Generated by Django 2.2 on 2019-04-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0100_randomchecktask_enterprise_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomchecktask',
            name='check_type',
            field=models.IntegerField(default=0, verbose_name='抽查方式'),
        ),
        migrations.AlterField(
            model_name='randomchecktask',
            name='enterprise_number',
            field=models.IntegerField(default=0, verbose_name='抽检企业数或企业比例'),
        ),
    ]
