# Generated by Django 2.1.7 on 2019-04-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0100_randomchecktask_enterprise_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('status', models.IntegerField(verbose_name='状态')),
            ],
            options={
                'verbose_name_plural': '行业版本',
            },
        ),
        migrations.AddField(
            model_name='majorindustry',
            name='versions',
            field=models.ManyToManyField(to='base.IndustryVersion'),
        ),
    ]
