# Generated by Django 2.1.7 on 2019-04-29 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0101_auto_20190428_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorySheet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='行业编号')),
                ('name', models.CharField(max_length=100, verbose_name='行业名称')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('status', models.IntegerField(verbose_name='状态')),
            ],
            options={
                'verbose_name_plural': '行业版本',
            },
        ),
        migrations.CreateModel(
            name='MajorIndustries',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='行业编号')),
                ('name', models.CharField(max_length=100, verbose_name='行业名称')),
                ('level', models.IntegerField(verbose_name='行业等级')),
                ('desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='行业描述')),
                ('ccc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.CCCIndustry', verbose_name='强制认证')),
                ('consumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.ConsumerIndustry', verbose_name='消费品')),
                ('historysheets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.HistorySheet', verbose_name='历史纪录表')),
                ('licence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.LicenceIndustry', verbose_name='许可证')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.MajorIndustries', verbose_name='上一级')),
            ],
            options={
                'verbose_name_plural': '重点产品目录',
            },
        ),
        migrations.RemoveField(
            model_name='majorindustry',
            name='versions',
        ),
        migrations.DeleteModel(
            name='IndustryVersion',
        ),
    ]
