# Generated by Django 2.1.7 on 2019-04-30 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0102_auto_20190429_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryIndustries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('status', models.IntegerField(verbose_name='状态')),
            ],
            options={
                'verbose_name_plural': '行业版本',
            },
        ),
        migrations.RemoveField(
            model_name='majorindustries',
            name='historysheets',
        ),
        migrations.AlterField(
            model_name='majorindustries',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='行业编号'),
        ),
        migrations.DeleteModel(
            name='HistorySheet',
        ),
        migrations.AddField(
            model_name='historyindustries',
            name='industries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.MajorIndustries', verbose_name='工业产品'),
        ),
    ]
