# Generated by Django 2.1.7 on 2019-04-30 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0103_auto_20190430_1506'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historyindustries',
            table='base_history_majorindustries',
        ),
    ]
