# Generated by Django 2.2 on 2019-05-05 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0104_auto_20190430_1513'),
        ('base', '0101_auto_20190429_1038'),
    ]

    operations = [
    ]
