# Generated by Django 2.2 on 2019-05-05 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0105_merge_20190505_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='majorindustries',
            options={'verbose_name_plural': '重点产品目录(新)'},
        ),
        migrations.RemoveField(
            model_name='majorindustries',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='majorindustries',
            name='name',
        ),
    ]
