# Generated by Django 2.2 on 2019-05-05 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0106_auto_20190505_1128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoryIndustries',
        ),
    ]
