# Generated by Django 2.2 on 2019-05-05 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0109_auto_20190505_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historyindustries',
            options={'verbose_name_plural': '重点产品目录历史版本'},
        ),
    ]
