# Generated by Django 2.2 on 2019-05-05 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0110_auto_20190505_1553'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoryIndustries',
        ),
    ]
