# Generated by Django 2.2 on 2019-05-06 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0112_historyindustries'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='new_industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.MajorIndustries', verbose_name='新产品类别'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='new_industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.MajorIndustries', verbose_name='新产品类别'),
        ),
    ]
