# Generated by Django 2.2 on 2019-05-07 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0113_auto_20190506_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='new_industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.MajorIndustries', verbose_name='新产品类别'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='new_industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.MajorIndustries', verbose_name='新产品类别'),
        ),
    ]
