# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-13 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskConf',
        ),
    ]
